version: "2"

services:
        nginx-proxy:
                image: nginxproxy/nginx-proxy
                volumes:
                        - conf:/etc/nginx/conf.d
                        - vhost:/etc/nginx/vhost.d
                        - html:/usr/share/nginx/html
                        - dhparam:/etc/nginx/dhparam
                        - certs:/etc/nginx/certs:ro
                        - /var/run/docker.sock:/tmp/docker.sock:ro
                        - ./vhost.d:/etc/nginx/vhost.d:ro
                ports:
                        - "80:80"
                        - "443:443"
                networks:
                        - default


        acme:
                image: nginxproxy/acme-companion
                environment:
                        DEFAULT_EMAIL: "${LETSENCRYPT_EMAIL}"
                depends_on:
                        - nginx-proxy
                volumes_from:
                        - nginx-proxy
                volumes:
                        - certs:/etc/nginx/certs:rw
                        - acme:/etc/acme.sh
                        - /var/run/docker.sock:/var/run/docker.sock:ro
                networks:
                        - default

volumes:
        conf:
        vhost:
        html:
        certs:
        dhparam:
        acme:

networks:
        default:
